name: CI - Release on main merges

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    name: Tag & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Skip if not a PR merge
        if: "!contains(github.event.head_commit.message, 'Merge pull request')"
        run: |
          echo "Not a PR merge, skipping release."
          exit 78

      - name: Compute tag
        id: tag
        run: |
          # Tag horodaté (ex: v2025.10.07-1215)
          TAG="v$(date -u +'%Y.%m.%d-%H%M')"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create and push git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ steps.tag.outputs.tag }}" -m "Release ${{ steps.tag.outputs.tag }}"
          git push origin "${{ steps.tag.outputs.tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
